#!/usr/bin/env node
// Regenerates the lesson catalog section of README.md from docs/catalog/lessons.json.
// Everything between <!-- catalog:start --> and <!-- catalog:end --> is owned by this script.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..', '..');
const README = path.join(ROOT, 'README.md');
const PAGES = 'https://dantech0xff.github.io/dreams/';
const START = '<!-- catalog:start -->';
const END = '<!-- catalog:end -->';

const catalog = JSON.parse(fs.readFileSync(path.join(ROOT, 'docs', 'catalog', 'lessons.json'), 'utf8'));

const bolts = (n) => '⚡'.repeat(n);
const cell = (s) => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
const mode = (l) => (l.renderMode === 'RENDER_EFFECT' ? 'RenderEffect' : l.renderMode === 'CUSTOM' ? 'Showcase' : l.uniforms.some((u) => u.name === 'touchPos') ? 'Touch' : 'ShaderBrush');

let out = [];
out.push(START);
out.push('<!-- Generated by tools/shader-catalog/update-readme.mjs from docs/catalog/lessons.json — do not edit by hand. -->');
out.push('');
out.push(`**${catalog.lessons.length} lessons in ${catalog.categories.length} categories.** Every thumbnail below was rendered from the lesson's own AGSL by [\`tools/shader-catalog\`](tools/shader-catalog); click one to open it live in the [web gallery](${PAGES}).`);
out.push('');
out.push('| Category | Lessons | Theme | Kind |');
out.push('|---|:-:|---|---|');
for (const c of catalog.categories) {
  const ls = catalog.lessons.filter((l) => l.category === c.name);
  const kinds = [...new Set(ls.map(mode))].join(', ');
  out.push(`| [${c.displayName}](#${c.displayName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}) | ${ls.length} | ${cell(c.tagline)} | ${kinds} |`);
}
out.push('');
for (const c of catalog.categories) {
  const ls = catalog.lessons.filter((l) => l.category === c.name);
  out.push(`### ${c.displayName}`);
  out.push('');
  out.push(`<sub>${ls.length} lessons · ${cell(c.tagline)} · [open category live ↗](${PAGES}#cat-${c.name.toLowerCase()})</sub>`);
  out.push('');
  out.push('| | Lesson | The idea | Play with |');
  out.push('|:-:|---|---|---|');
  for (const l of ls) {
    const img = `<a href="${PAGES}#${l.id}"><img src="docs/gallery/${l.id}.png" width="96" alt="${cell(l.title)}"></a>`;
    const src = `${l.source.file}#L${l.source.line}`;
    const controls = l.controls.length ? l.controls.map((k) => `\`${k.name}\``).join(' ') : '—';
    const kind = mode(l);
    const kindNote = kind === 'ShaderBrush' ? '' : ` · ${kind}`;
    out.push(`| ${img} | **[${cell(l.title)}](${src})**<br><sub>${bolts(l.complexity)}${kindNote}<br>\`${l.id}\`</sub> | ${cell(l.conceptIntro)} | ${controls} |`);
  }
  out.push('');
}
out.push(END);

const readme = fs.readFileSync(README, 'utf8');
const s = readme.indexOf(START);
const e = readme.indexOf(END);
if (s < 0 || e < 0) throw new Error(`README.md is missing the ${START} / ${END} markers`);
const next = readme.slice(0, s) + out.join('\n') + readme.slice(e + END.length);
if (next !== readme) {
  fs.writeFileSync(README, next);
  console.log('Updated README.md lesson catalog');
} else {
  console.log('README.md lesson catalog already up to date');
}
